apiVersion: v1
kind: Service

metadata:
  name: {{ include "storage-lab.fullname" . }}

  labels:
    {{- include "storage-lab.labels" . | nindent 4 }}

spec:
  type: {{ .Values.service.type }}

  selector:
    app: {{ .Values.labels.app }}
    tier: {{ .Values.labels.tier }}

  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}

      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}